---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-02-10 - 09:28:49 +0000
  labels:
    app.kubernetes.io/name: postman
    app.kubernetes.io/part-of: postman
    app.kubernetes.io/version: 1.0.0
    app.openshift.io/runtime: quarkus
  name: postman
spec:
  replicas: 1
  selector:
    app.kubernetes.io/part-of: postman
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: postman
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/build-timestamp: 2023-02-10 - 09:28:49 +0000
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/part-of: postman
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: postman
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: postman:1.0.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: postman
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - postman
        from:
          kind: ImageStreamTag
          name: postman:1.0.0
      type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-02-10 - 09:28:49 +0000
  labels:
    app.kubernetes.io/name: postman
    app.kubernetes.io/part-of: postman
    app.kubernetes.io/version: 1.0.0
    app.openshift.io/runtime: quarkus
  name: postman
spec:
  dockerImageRepository: docker.io/huuhoait/postman
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-02-10 - 09:28:49 +0000
  labels:
    app.kubernetes.io/name: postman
    app.kubernetes.io/part-of: postman
    app.kubernetes.io/version: 1.0.0
    app.openshift.io/runtime: quarkus
  name: postman
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: postman
    app.kubernetes.io/part-of: postman
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
